FROM mirror.gcr.io/library/caddy:2.10.0-builder AS builder

RUN xcaddy build \
    --with github.com/porech/caddy-maxmind-geolocation

FROM mirror.gcr.io/library/caddy:2.10.0

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

RUN adduser -H -D -u 1000 app