FROM mirror.gcr.io/library/ubuntu:24.04

COPY lib/base/rootfs /
RUN --mount=type=cache,sharing=locked,target=/var/lib/apt \
    --mount=type=cache,sharing=locked,target=/var/cache/apt \
    /build/setup-base.sh

COPY lib/ssh/rootfs /
RUN --mount=type=cache,sharing=locked,target=/var/lib/apt \
    --mount=type=cache,sharing=locked,target=/var/cache/apt \
    /build/setup-ssh.sh

ARG PHP_VERSION

COPY lib/php/rootfs /
RUN --mount=type=cache,sharing=locked,target=/var/lib/apt \
    --mount=type=cache,sharing=locked,target=/var/cache/apt \
    /build/setup-php.sh

COPY lib/php-composer/rootfs /
RUN /build/setup-php-composer.sh

COPY lib/wp-cli/rootfs /
RUN /build/setup-wp-cli.sh
